### PR TITLE
[Chore] Release first minor version 0.1.0 

### LINKED ISSUE #25: [Chore] Release first minor version 0.1.0
## Why

Release first minor version 0.1.0 as all fundamental features are completed.
 
## Who Benefits?
- Developer
- Tester

### PR DESCRIPTION
**Pull request by Shayokh144**
https://github.com/nimblehq/ci-cd-sample-ios/issues/25

## What happened

Release version 0.1.0 

## Insight

- Bump build version
- Add trigger option in Bitrise
-  Add release note
 
## Proof Of Work

N/A

### CODE REVIEW

**Comment by Shayokh144** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is quite big, more than 500 lines of changes.</td>
    </tr>
  </tbody>
</table>

## Current coverage for WeatherToday.app is `75.38%`
Files changed | - | - 
--- | --- | ---
LocalizedString.swift | `0.00%` | :skull:
Configuration.swift | `88.89%` | :white_check_mark:
WeatherViewController.swift | `90.43%` | :white_check_mark:
GetWeatherUseCase.swift | `100.00%` | :white_check_mark:
WeatherRepository.swift | `100.00%` | :white_check_mark:
WeatherViewModel.swift | `100.00%` | :white_check_mark:
MockWeatherUseCase.swift | `100.00%` | :white_check_mark:
WeatherApiRequestConfigurations.swift | `100.00%` | :white_check_mark:
WeatherApi.swift | `100.00%` | :white_check_mark:

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

## Coverage Table

Files changed | - | - 
--- | --- | ---
LocalizedString.swift | `0.00%` | :skull:
Optional+Unwrap.swift | `0.00%` | :skull:
Color+Application.swift | `0.00%` | :skull:
UIView+Subviews.swift | `0.00%` | :skull:
Navigator.swift | `0.00%` | :skull:
RequestConfiguration.swift | `75.00%` | :warning:
Configuration.swift | `88.89%` | :white_check_mark:
WeatherViewController.swift | `90.43%` | :white_check_mark:
NetworkAPIProtocol.swift | `95.74%` | :white_check_mark:
WeatherNetworkAPI.swift | `100.00%` | :white_check_mark:
GetWeatherUseCase.swift | `100.00%` | :white_check_mark:
WeatherRepository.swift | `100.00%` | :white_check_mark:
AppDelegate.swift | `100.00%` | :white_check_mark:
WeatherViewModel.swift | `100.00%` | :white_check_mark:
MockWeatherUseCase.swift | `100.00%` | :white_check_mark:
WeatherApiRequestConfigurations.swift | `100.00%` | :white_check_mark:
WeatherApi.swift | `100.00%` | :white_check_mark:

---



<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by blyscuit — APPROVED** [review]
Please create another PR to bring changes in this release to `develop`.

**Review by vnntsu — APPROVED** [review]
I prefer to correct the release process at the next time.
You can learn more [Release Management](https://nimblehq.co/compass/development/version-control/release-management/)

**Comment by Shayokh144** [comment]
@vnntsu thank you.. will follow this next time.

**Pull request merged**
